name: Update GitHub Activity

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    name: Update Activity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ update recent transmissions"
          MAX_LINES: 5
